import "./styles/global.css";

import { Poppins, Montserrat } from "next/font/google";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import RegisterUser from "./pages/registerUser";
import NewSeller from "./pages/newSeller";
import DetailProduct from "./pages/detailProduct";
import { Footer } from "./components/footer";
import { UserProvider } from "./contexts/userContext";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={poppins.className}>
          <Navbar
            links={[
              { name: "Inicio", link: "/" },
              { name: "Catálogo", link: "/search" },
            ]}
          />

          <main>{children}</main>

          <Footer></Footer>
        </body>
      </html>
    </UserProvider>
  );
}
